apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ settings.proxy.storage_size_per_user | default("2Gi", true) }}
  storageClassName: rook-cephfs
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-shinyproxy
spec:
  ingress:
    - from: 
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ settings.proxy.namespace | default("shinyproxy", true)}}
  podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-only-namespace
spec:
  ingress:
    - from:
        - podSelector: {}
  podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress
spec:
  egress: [{}]
  podSelector: {}
  policyTypes:
  - Egress
